<?php
/*
 * This file is generated by divaa-backup
 * Do not edit this file manually
 */

$config = [
    [
        'code'      =>  'optus-stage',
        'token'     =>  'a901805703b60203bba0ae190f31d618',
        'db_user'   =>  'optus_stage122023',
        'db_pass'   =>  'D6d3~4g7t',
        'db'        =>  'optus_stage122023',
    ],
];
