<?php
require 'vendor/autoload.php';
// Load the config file
require_once 'config.php';
$allowedIps = ['127.0.0.1','116.74.77.96'];

header("Content-Type: application/json");

$response = [
    'status'    =>  false,
    'message'   =>  '',
];

if ($_SERVER['REQUEST_METHOD'] != 'POST') {
    $response['message'] = 'Invalid request';
    echo json_encode($response);
    exit;
}

/*if(!in_array($_SERVER['REMOTE_ADDR'],$allowedIps)) {
    $response['message'] = 'Access denied';
    echo json_encode($response);
    exit;
}*/

if(!isset($_POST['code']) || !$_POST['code'] || !isset($_POST['token']) || !$_POST['token'] || !isset($_POST['new_token']) || !$_POST['new_token']) {
    $response['message'] = 'Invalid request';
    echo json_encode($response);
    exit;
}

$code = $_POST['code'];
$token = $_POST['token'];
$newToken = $_POST['new_token'];

$configs = [];
foreach ($config as $c) {
    if($c['code'] == $code && $c['token'] == $token) {
        $c['token'] = $newToken;
    }
    $configs[] = $c;
}
// update config.php with new token
$configFile = fopen("config.php", "w") or die("Unable to open file!");
fwrite($configFile, "<?php\n");
fwrite($configFile, "/*\n");
fwrite($configFile, " * This file is generated by divaa-backup\n");
fwrite($configFile, " * Do not edit this file manually\n");
fwrite($configFile, " */\n");
fwrite($configFile, "\n");
fwrite($configFile, '$config = [');
fwrite($configFile, "\n");
foreach ($configs as $c) {
    fwrite($configFile, "    [\n");
    fwrite($configFile, "        'code'      =>  '{$c['code']}',\n");
    fwrite($configFile, "        'token'     =>  '{$c['token']}',\n");
    fwrite($configFile, "        'db_user'   =>  '{$c['db_user']}',\n");
    fwrite($configFile, "        'db_pass'   =>  '{$c['db_pass']}',\n");
    fwrite($configFile, "        'db'        =>  '{$c['db']}',\n");
    fwrite($configFile, "    ],\n");
}
fwrite($configFile, "];\n");
fclose($configFile);

$response['status'] = true;
$response['message'] = 'Token updated successfully';
echo json_encode($response);
exit;